final List<Map<String, dynamic>> products = [
  {
    'id': '1',
    'title': 'Luminous UPS',
    'variant': '600VA',
    'price': 2999.0,
    'image': 'assets/images/luminousups.jpg',
    'categories': 'Inverter',
    'popularProduct': true,
    'trendingProduct': false,
    'featuredproducts': true,
    'description': 'Reliable UPS for your power needs.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Luminous UPS (600VA). Reliable UPS for your power needs.',
    'rating': 4.2,
    'ratingCount': 85,
  },
  {
    'id': '2',
    'title': 'Amaron Battery',
    'variant': '150Ah',
    'price': 7500.0,
    'image': 'assets/images/amron150.jpg',
    'categories': 'Battery',
    'popularProduct': true,
    'trendingProduct': false,
    'featuredproducts': true,
    'description': 'High capacity battery for long backup.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Amaron Battery (150Ah). High capacity battery for long backup.',
    'rating': 4.5,
    'ratingCount': 64,
  },
  {
    'id': '3',
    'title': 'Microtek Inverter',
    'variant': '800VA',
    'price': 4200.0,
    'image': 'assets/images/microtexinv.jpg',
    'categories': 'Inverter',
    'popularProduct': false,
    'trendingProduct': false,
    'featuredproducts': true,
    'description': 'Compact inverter for home usage.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Microtek Inverter (800VA). Compact inverter for home usage.',
    'rating': 4.1,
    'ratingCount': 39,
  },
  {
    'id': '4',
    'title': 'Livguard Tubular Battery',
    'variant': '200Ah',
    'price': 9500.0,
    'image': 'assets/images/livguard.jpg',
    'categories': 'Battery',
    'popularProduct': true,
    'trendingProduct': false,
    'featuredproducts': false,
    'description': 'Durable battery with long life.',
    'isfav': true,
    'detaileddescription':
        'Detailed specs and information about Livguard Tubular Battery (200Ah). Durable battery with long life.',
    'rating': 4.7,
    'ratingCount': 91,
  },
  {
    'id': '5',
    'title': 'Exide Solar Panel',
    'variant': '150W',
    'price': 3300.0,
    'image': 'assets/images/solar.png',
    'categories': 'Solar System',
    'popularProduct': true,
    'trendingProduct': true,
    'featuredproducts': false,
    'description': 'Solar panel for eco-friendly energy.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Exide Solar Panel (150W). Solar panel for eco-friendly energy.',
    'rating': 4.0,
    'ratingCount': 73,
  },
  {
    'id': '6',
    'title': 'Water Distiller',
    'variant': '5L/hr',
    'price': 2800.0,
    'image': 'assets/images/distiller.jpg',
    'categories': 'Distill Water',
    'popularProduct': false,
    'trendingProduct': false,
    'featuredproducts': false,
    'description': 'Purify your water efficiently.',
    'isfav': true,
    'detaileddescription':
        'Detailed specs and information about Water Distiller (5L/hr). Purify your water efficiently.',
    'rating': 3.8,
    'ratingCount': 22,
  },
  {
    'id': '7',
    'title': 'DM Water Can',
    'variant': '20L',
    'price': 120.0,
    'image': 'assets/images/dmwater.jpeg',
    'categories': 'DM Water',
    'popularProduct': true,
    'trendingProduct': false,
    'featuredproducts': false,
    'description': 'For lab and industrial use.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about DM Water Can (20L). For lab and industrial use.',
    'rating': 4.6,
    'ratingCount': 57,
  },
  {
    'id': '8',
    'title': 'Microtek Solar UPS',
    'variant': '850VA',
    'price': 6200.0,
    'image': 'assets/images/solarups.jpg',
    'categories': 'Online Ups',
    'popularProduct': true,
    'trendingProduct': false,
    'featuredproducts': false,
    'description': 'UPS with solar charging option.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Microtek Solar UPS (850VA). UPS with solar charging option.',
    'rating': 4.3,
    'ratingCount': 49,
  },
  {
    'id': '9',
    'title': 'Luminous EcoVolt',
    'variant': '1050VA',
    'price': 4600.0,
    'image': 'assets/images/ecovolt.jpg',
    'categories': 'Inverter',
    'popularProduct': false,
    'trendingProduct': false,
    'featuredproducts': false,
    'description': 'Pure sine wave inverter for homes.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Luminous EcoVolt (1050VA). Pure sine wave inverter for homes.',
    'rating': 4.4,
    'ratingCount': 65,
  },
  {
    'id': '10',
    'title': 'Rocket SMF Battery',
    'variant': '12V 42Ah',
    'price': 3300.0,
    'image': 'assets/images/smf.png',
    'categories': 'Battery',
    'popularProduct': false,
    'trendingProduct': true,
    'featuredproducts': false,
    'description': 'Sealed maintenance free battery.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Rocket SMF Battery (12V 42Ah). Sealed maintenance free battery.',
    'rating': 3.9,
    'ratingCount': 34,
  },

  {
    'id': '11',
    'title': 'Su-Kam Inverter',
    'variant': '1100VA',
    'price': 5100.0,
    'image': 'assets/images/sukam.jpg',
    'categories': 'Inverter',
    'popularProduct': false,
    'trendingProduct': false,
    'featuredproducts': false,
    'description': 'Trusted brand for inverters.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Su-Kam Inverter (1100VA). Trusted brand for inverters.',
    'rating': 4.0,
    'ratingCount': 53,
  },
  {
    'id': '12',
    'title': 'Solar Charge Controller',
    'variant': '20A',
    'price': 900.0,
    'image': 'assets/images/controller.jpg',
    'categories': 'Solar System',
    'popularProduct': true,
    'trendingProduct': false,
    'featuredproducts': false,
    'description': 'Protect your batteries from overcharging.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Solar Charge Controller (20A). Protect your batteries from overcharging.',
    'rating': 4.3,
    'ratingCount': 47,
  },
  {
    'id': '13',
    'title': 'Pure DM Water',
    'variant': '10L Can',
    'price': 80.0,
    'image': 'assets/images/dmcan.jpg',
    'categories': 'DM Water',
    'popularProduct': false,
    'trendingProduct': false,
    'featuredproducts': false,
    'description': 'Double distilled mineral-free water.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Pure DM Water (10L Can). Double distilled mineral-free water.',
    'rating': 4.1,
    'ratingCount': 33,
  },
  {
    'id': '14',
    'title': 'Distilled Water Bottle',
    'variant': '1L',
    'price': 25.0,
    'image': 'assets/images/water1.png',
    'categories': 'Distill Water',
    'popularProduct': false,
    'trendingProduct': false,
    'featuredproducts': false,
    'description': 'For medical and cleaning uses.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Distilled Water Bottle (1L). For medical and cleaning uses.',
    'rating': 4.5,
    'ratingCount': 78,
  },
  {
    'id': '15',
    'title': 'UPS Combo Set',
    'variant': '800VA + Battery',
    'price': 11999.0,
    'image': 'assets/images/upscombo.jpg',
    'categories': 'Online Ups',
    'popularProduct': true,
    'trendingProduct': false,
    'featuredproducts': false,
    'description': 'UPS and battery combo offer.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about UPS Combo Set (800VA + Battery). UPS and battery combo offer.',
    'rating': 4.6,
    'ratingCount': 89,
  },
  {
    'id': '16',
    'title': 'Axion Inverter Battery',
    'variant': '180Ah',
    'price': 6800.0,
    'image': 'assets/images/axion.jpg',
    'categories': 'Battery',
    'popularProduct': false,
    'trendingProduct': false,
    'featuredproducts': false,
    'description': 'Robust and long lasting power.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Axion Inverter Battery (180Ah). Robust and long lasting power.',
    'rating': 4.2,
    'ratingCount': 40,
  },
  {
    'id': '17',
    'title': 'SF Sonic Battery',
    'variant': '12V 135Ah',
    'price': 5900.0,
    'image': 'assets/images/sonic.jpg',
    'categories': 'Battery',
    'popularProduct': false,
    'trendingProduct': false,
    'featuredproducts': false,
    'description': 'Ideal for household UPS.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about SF Sonic Battery (12V 135Ah). Ideal for household UPS.',
    'rating': 4.3,
    'ratingCount': 61,
  },
  {
    'id': '18',
    'title': 'Solar Kit Basic',
    'variant': '100W Panel',
    'price': 3500.0,
    'image': 'assets/images/solarkit.jpg',
    'categories': 'Solar System',
    'popularProduct': false,
    'trendingProduct': false,
    'featuredproducts': false,
    'description': 'Basic kit to start solar at home.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Solar Kit Basic (100W Panel). Basic kit to start solar at home.',
    'rating': 4.0,
    'ratingCount': 45,
  },
  {
    'id': '19',
    'title': 'Premium Inverter',
    'variant': 'Digital LCD 1kVA',
    'price': 6999.0,
    'image': 'assets/images/premium.jpg',
    'categories': 'Inverter',
    'popularProduct': true,
    'trendingProduct': false,
    'featuredproducts': false,
    'description': 'Digital inverter with advanced display.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Premium Inverter (Digital LCD 1kVA). Digital inverter with advanced display.',
    'rating': 4.7,
    'ratingCount': 94,
  },
  {
    'id': '20',
    'title': 'Water Purifier UPS',
    'variant': '12V Backup',
    'price': 2499.0,
    'image': 'assets/images/purups.jpg',
    'categories': 'Online Ups',
    'popularProduct': false,
    'trendingProduct': false,
    'featuredproducts': false,
    'description': 'Backup UPS for RO systems.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Water Purifier UPS (12V Backup). Backup UPS for RO systems.',
    'rating': 4.1,
    'ratingCount': 37,
  },
  {
    'id': '21',
    'title': 'Blue Star Battery',
    'variant': '160Ah',
    'price': 6700.0,
    'image': 'assets/images/bluestar1.jpg',
    'categories': 'Battery',
    'popularProduct': false,
    'trendingProduct': true,
    'featuredproducts': false,
    'description': 'Reliable heavy-duty battery.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Blue Star Battery (160Ah). Reliable heavy-duty battery.',
    'rating': 4.5,
    'ratingCount': 55,
  },
  {
    'id': '22',
    'title': 'Luminous Gel Battery',
    'variant': '120Ah',
    'price': 7700.0,
    'image': 'assets/images/gel.jpg',
    'categories': 'Battery',
    'popularProduct': true,
    'trendingProduct': false,
    'featuredproducts': false,
    'description': 'Maintenance-free gel-based battery.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Luminous Gel Battery (120Ah). Maintenance-free gel-based battery.',
    'rating': 4.8,
    'ratingCount': 96,
  },
  {
    'id': '23',
    'title': 'Digital Solar UPS',
    'variant': '1200VA',
    'price': 7500.0,
    'image': 'assets/images/digsolar.jpg',
    'categories': 'Solar System',
    'popularProduct': true,
    'trendingProduct': false,
    'featuredproducts': false,
    'description': 'Digital display solar inverter.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Digital Solar UPS (1200VA). Digital display solar inverter.',
    'rating': 4.4,
    'ratingCount': 68,
  },
  {
    'id': '24',
    'title': 'RO Booster Pump',
    'variant': '100 GPD',
    'price': 1800.0,
    'image': 'assets/images/booster.jpg',
    'categories': 'Distill Water',
    'popularProduct': false,
    'trendingProduct': false,
    'featuredproducts': false,
    'description': 'For improved water purification.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about RO Booster Pump (100 GPD). For improved water purification.',
    'rating': 4.1,
    'ratingCount': 44,
  },
  {
    'id': '25',
    'title': 'Advanced Solar Grid',
    'variant': '3kW',
    'price': 45000.0,
    'image': 'assets/images/grid.jpg',
    'categories': 'Solar System',
    'popularProduct': true,
    'trendingProduct': true,
    'featuredproducts': false,
    'description': 'Heavy-duty grid for residential solar.',
    'isfav': false,
    'detaileddescription':
        'Detailed specs and information about Advanced Solar Grid (3kW). Heavy-duty grid for residential solar.',
    'rating': 4.9,
    'ratingCount': 98,
  },
];
